- name: Install pyenv
  git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: '/home/{{ ansible_user }}/.pyenv'
    version: 'master'
    update: no

- name: Add pyenv to profile
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'export PATH="$HOME/.pyenv/bin:$PATH"'
    state: present
  notify:
    - Reload bashrc

- name: Install Python version using pyenv
  pyenv:
    name: "{{ item.python_version }}"
    state: present
  with_items: "{{ python_virtualenvs }}"

- name: Create virtual environment
  command: "{{ ansible_user }}/.pyenv/versions/{{ item.python_version }}/bin/python -m venv /home/{{ ansible_user }}/.virtualenvs/{{ item.name }}"
  with_items: "{{ python_virtualenvs }}"
  creates: "/home/{{ ansible_user }}/.virtualenvs/{{ item.name }}"

- name: Install required packages in the virtual environment
  pip:
    virtualenv: "/home/{{ ansible_user }}/.virtualenvs/{{ item.name }}"
    name: "{{ item.packages }}"
  with_items: "{{ python_virtualenvs }}"
