- name: Install python3 and python3-venv packages
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
    state: present
    update_cache: yes

- name: Create Python virtual environment
  command: python3 -m venv "{{ venv_path }}"
  creates: "{{ venv_path }}/bin/activate"

- name: Install required Python packages
  pip:
    name: "{{ item }}"
    virtualenv: "{{ venv_path }}"
  with_items: "{{ python_packages }}"
  when: python_packages is defined

- name: Install Jupyter
  pip:
    name: jupyter
    virtualenv: "{{ venv_path }}"

- name: Create symbolic link for Jupyter
  file:
    src: "{{ venv_path }}/bin/jupyter"
    dest: "/usr/local/bin/jupyter"
    state: link
