- name: Install Python 3 and pip
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Create Python virtual environments
  shell: |
    python3 -m venv {{ item }}
  loop: "{{ python_envs }}"
  args:
    creates: "{{ item }}/bin/activate"

- name: Install packages in each environment
  pip:
    name: "{{ item.packages }}"
    virtualenv: "{{ item.env_path }}"
  loop: "{{ python_envs }}"

- name: Install Jupyter in the main environment
  pip:
    name: jupyter
    virtualenv: "{{ python_envs[0].env_path }}"

- name: Create symbolic link for Jupyter
  file:
    src: "{{ python_envs[0].env_path }}/bin/jupyter"
    dest: "/usr/local/bin/jupyter"
    state: link
