- name: Install dependencies for pyenv
  package:
    name:
      - "git"
      - "gcc"
      - "make"
      - "libffi-dev"
      - "libssl-dev"
      - "zlib1g-dev"
    state: present

- name: Install pyenv
  git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: '/home/{{ ansible_user }}/.pyenv'
    version: 'master'
    update: no

- name: Add pyenv to bashrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'export PATH="$HOME/.pyenv/bin:$PATH"'
    state: present
  notify:
    - Reload bashrc

- name: Install required Python versions using pyenv
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    pyenv install {{ item.python_version }}
  with_items: "{{ python_virtualenvs }}"
  notify:
    - Reload bashrc

- name: Create Python virtual environment
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    pyenv activate {{ item.python_version }}
    python -m venv /home/{{ ansible_user }}/.virtualenvs/{{ item.name }}
  with_items: "{{ python_virtualenvs }}"
  creates: "/home/{{ ansible_user }}/.virtualenvs/{{ item.name }}"

- name: Install required packages in the virtual environment
  pip:
    virtualenv: "/home/{{ ansible_user }}/.virtualenvs/{{ item.name }}"
    name: "{{ item.packages }}"
  with_items: "{{ python_virtualenvs }}"
