- name: Install Pyenv
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ pyenv_path }}"
    version: "master"

- name: Add pyenv to shell profile
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: 'export PATH="{{ pyenv_path }}/bin:$PATH"'
    create: yes

- name: Initialize pyenv in the shell
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: 'export PYENV_ROOT="{{ pyenv_path }}"'
    create: yes

- name: Get installed python versions using pyenv
  command:
    cmd: "{{ pyenv_path }}/bin/pyenv versions --bare"
  register: pyenv_versions

- name: Install Python versions using pyenv
  command:
    cmd: "{{ pyenv_path }}/bin/pyenv install {{ item }}"
  loop: "{{ python_versions }}"
  when: "'{{ item }}' not in pyenv_versions.stdout_lines"

- name: Create virtual environments
  command:
    cmd: "{{ pyenv_path }}/versions/{{ item.python_version }}/bin/python -m venv {{ virtualenvs_path }}/{{ item.name }}"
  loop: "{{ virtualenvs }}"

- name: Install Python packages in virtual environment
  pip:
    name: "{{ item.packages }}"
    virtualenv: "{{ virtualenvs_path }}/{{ item.name }}"
  loop: "{{ virtualenvs }}"
